<?php
require_once PPLIBPATH . 'HTML/Admin/Widgets/Objects/interface.inc';

require_once PPLIBPATH . 'HTML/Admin/Widgets/Objects/abstract.class.inc';
require_once PPLIBPATH . 'HTML/Admin/Widgets/Objects/table.class.inc';
require_once PPLIBPATH . 'HTML/Admin/Widgets/Objects/tree.class.inc';

require_once PPLIBPATH . 'HTML/Admin/Widgets/Objects/ajaxtree.class.inc';

require_once PPLIBPATH . 'HTML/Admin/Widgets/Objects/blockstree.class.inc';
