<?php
	require_once 'abstract.class.inc';
	
	require_once 'index.class.inc';
	require_once 'action.class.inc';
	require_once 'json.class.inc';
	require_once 'sbin.class.inc';
	require_once 'captcha.class.inc';

	require_once 'Admin/abstract.class.inc';

	require_once 'Admin/index.class.inc';
	require_once 'Admin/popup.class.inc';
	require_once 'Admin/action.class.inc';
	require_once 'Admin/json.class.inc';
?>