<?php

	require_once PPLIBPATH . 'Config/Description/Bindings/default.class.inc';

	require_once PPLIBPATH . 'Config/Description/Bindings/struct.class.inc';
	require_once PPLIBPATH . 'Config/Description/Bindings/struct-type.class.inc';
	require_once PPLIBPATH . 'Config/Description/Bindings/struct-match.class.inc';
	require_once PPLIBPATH . 'Config/Description/Bindings/content.class.inc';
	require_once PPLIBPATH . 'Config/Description/Bindings/subcontent.class.inc';

	require_once PPLIBPATH . 'Config/Description/Bindings/main.class.inc';
	require_once PPLIBPATH . 'Config/Description/Bindings/types.class.inc';
