<?php

require_once PPLIBPATH . 'StorageType/abstract.class.inc';

require_once PPLIBPATH . 'StorageType/string.class.inc';
require_once PPLIBPATH . 'StorageType/integer.class.inc';
require_once PPLIBPATH . 'StorageType/bigint.class.inc';
require_once PPLIBPATH . 'StorageType/pk.class.inc';
require_once PPLIBPATH . 'StorageType/float.class.inc';
require_once PPLIBPATH . 'StorageType/boolean.class.inc';
require_once PPLIBPATH . 'StorageType/timestamp.class.inc';

require_once PPLIBPATH . 'StorageType/serialized.class.inc';
require_once PPLIBPATH . 'StorageType/yaml.class.inc';

require_once PPLIBPATH . 'StorageType/array.class.inc';
require_once PPLIBPATH . 'StorageType/intarray.class.inc';
require_once PPLIBPATH . 'StorageType/flatintarray.class.inc';

require_once PPLIBPATH . 'StorageType/File/abstract.class.inc';
require_once PPLIBPATH . 'StorageType/File/file.class.inc';
require_once PPLIBPATH . 'StorageType/File/image.class.inc';
require_once PPLIBPATH . 'StorageType/File/flash.class.inc';
require_once PPLIBPATH . 'StorageType/File/filesarray.class.inc';
require_once PPLIBPATH . 'StorageType/File/imagesarray.class.inc';
require_once PPLIBPATH . 'StorageType/File/flashsarray.class.inc';

require_once PPLIBPATH . 'StorageType/virtual.class.inc';
require_once PPLIBPATH . 'StorageType/aggr.class.inc';
require_once PPLIBPATH . 'StorageType/session_st.class.inc';

require_once PPLIBPATH . 'StorageType/sql.class.inc';
