<?php
require_once('HTML/Admin/Widgets/abstract.class.inc');

require_once('HTML/Admin/Widgets/Input/checkbox.class.inc');
require_once('HTML/Admin/Widgets/Input/hidden.class.inc');
require_once('HTML/Admin/Widgets/Input/color.class.inc');

require_once('HTML/Admin/Widgets/Input/input.class.inc');
require_once('HTML/Admin/Widgets/Input/password.class.inc');
require_once('HTML/Admin/Widgets/Input/textarea.class.inc');
require_once('HTML/Admin/Widgets/Input/richedit.class.inc');

require_once('HTML/Admin/Widgets/Input/Datetime/date.class.inc');
require_once('HTML/Admin/Widgets/Input/Datetime/datehidden.class.inc');
require_once('HTML/Admin/Widgets/Input/Datetime/datecalendar.class.inc');
require_once('HTML/Admin/Widgets/Input/Datetime/time.class.inc');
require_once('HTML/Admin/Widgets/Input/Datetime/timehidden.class.inc');


require_once('HTML/Admin/Widgets/Input/file.class.inc');
require_once('HTML/Admin/Widgets/Input/image.class.inc');
require_once('HTML/Admin/Widgets/Input/flash.class.inc');
require_once('HTML/Admin/Widgets/Input/link.class.inc');

require_once('HTML/Admin/Widgets/Input/dropdown.class.inc');
require_once('HTML/Admin/Widgets/Input/parentdropdown.class.inc');

require_once('HTML/Admin/Widgets/Input/table.class.inc');
require_once('HTML/Admin/Widgets/Input/ip.class.inc');


require_once('HTML/Admin/Widgets/Control/submit.class.inc');
require_once('HTML/Admin/Widgets/Control/button.class.inc');
require_once('HTML/Admin/Widgets/Control/close.class.inc');
require_once('HTML/Admin/Widgets/Control/reset.class.inc');

require_once('HTML/Admin/Widgets/pager.class.inc');
require_once('HTML/Admin/Widgets/table.class.inc');
require_once('HTML/Admin/Widgets/list.class.inc');
include_once 'HTML/Admin/Widgets/tablesimple.class.inc';
?>