<?php
/*
Proxima CMS web engine
(c) Dalee, 2003-2007

$Id$
*/
require_once 'maincommon.inc';

require_once 'HTML/Abstract/layout.class.inc';
require_once 'HTML/Abstract/htmlform.class.inc';

require_once 'HTML/form.class.inc';
require_once('HTML/Admin/layout.class.inc');
require_once('HTML/Admin/objectform.class.inc');

require_once('HTML/Admin/Widgets/classes.inc');

require_once(BASEPATH.'/local/lib/mainadmin.inc');
?>
