<?
/*
Proxima CMS web engine
(c) Dalee, 2003-2007

$Id: mainadmin.inc,v 1.9 2006/10/04 14:26:19 lynn Exp $
*/
require_once 'maincommon.inc';

require_once 'HTML/form.class.inc';

require_once 'HTML/Abstract/layout.class.inc';
require_once 'HTML/Abstract/htmlform.class.inc';

require_once 'HTML/Admin/layout.class.inc';
require_once 'HTML/Admin/objectform.class.inc';
require_once 'HTML/Admin/table.class.inc';
require_once 'HTML/Admin/tablesimple.class.inc';

require_once 'local/lib/mainadmin.inc';
?>
