<?php
require_once '../lib/mainuser.inc';
require_once PPLIBPATH . '/Security/blockingnumbers.class.inc';
require_once PPLIBPATH . '/Security/captcha.class.inc';

$request = PXRegistry::getRequest();
$blockingNumbers = new NLBlockingNumbers();

switch ($request->GetVar('action')) {
	default:
	case 'get_image':
		$k = (int)$request->GetVar('k');
		if (($str = $blockingNumbers->GetValueByKey($k)) == '') {
			$response = PXResponse::getInstance();
			$response->notFound();
			$response->send();
			exit;
		}

		$fonts = array(
			BASEPATH . '/libpp/share/fonts/tahoma.ttf'
		);

		$colors = array('lite' => 'FBFEFF', 'dark' => '545B5D');
		$width = mb_strlen($str) * 25;

		$captcha = new NLCaptcha($str, $width, 40, $fonts, $colors, false, 23);
		break;

	case 'get_code':
		$blockingNumbers->CreateNew(4, '23456789qweyupasdfkzxcvbnm23456789');
		print $blockingNumbers->key;
		break;
}

