<?php
	require_once '../lib/mainuser.inc';
	require_once BASEPATH.'/libpp/lib/Security/blockingnumbers.class.inc';
	require_once BASEPATH.'/libpp/lib/Security/captcha.class.inc';

	$request = PXRegistry::getRequest();
	$bn      = new NLBlockingNumbers();

	switch($request->GetVar('action')){
		default:
		case 'get_image':
			$k = (int)$request->GetVar('k');
			if (($str = $bn->GetValueByKey($k)) == '') {
				$response = PXResponse::getInstance();
				$response->notFound();
				$response->send();
				exit;
			}

			$fonts = array(
				BASEPATH.'/libpp/share/fonts/tahoma.ttf'
			);

			$colors = array('lite' => 'FBFEFF', 'dark' => '545B5D');
			$width  = mb_strlen($str) * 25;

			$captcha = new NLCaptcha($str, $width, 40, $fonts, $colors, false, 23);
		break;

		case 'get_code':
			$bn->CreateNew(4, '23456789qweyupasdfkzxcvbnm23456789');
			print $bn->key;
		break;
	}
?>
