<?
	$file = $_SERVER['HTTP_X_REWRITE_URL'];

	if (preg_match('/\.js$/i', $file)) {
		header("Content-Type: text/javascript; charset=utf8");
	} else {
		header("Content-Type: text/html; charset=utf8");
	}

	$s = @file_get_contents(substr($file, strpos(substr($file, 1), "/")+2));

	if ($s === false) {
		header("HTTP/1.0 404 Not found");
		exit;
	} else {
		include_once '../../lib/Common/functions.string.inc';
		echo myconv('k', 'w', $s);
	}

?>
